services:
  database-magma:
    image: mysql:8.0
    container_name: mysql-certificados-magma
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env 
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - magma-network

  django-magma:
    build: .
    container_name: application-certificados-magma
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - database-magma
    env_file:
      - .env
    networks:
      - magma-network

volumes:
  mysql_data:

networks:
  magma-network:
    driver: bridge