# Generated by Django 5.0.4 on 2024-04-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('front', models.FileField(upload_to='models/')),
                ('back', models.FileField(upload_to='models/')),
            ],
        ),
    ]
