# Generated by Django 5.0.4 on 2024-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_text_model_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
