# Generated by Django 5.0.4 on 2024-04-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_identifier'),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='model.model'),
            preserve_default=False,
        ),
    ]
