# Generated by Django 5.0.4 on 2024-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='texts',
        ),
        migrations.AddField(
            model_name='certificate',
            name='data_json',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
