# Generated by Django 5.0.4 on 2024-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('pos_x', models.CharField(max_length=200)),
                ('pos_y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='texts',
            field=models.ManyToManyField(to='model.text'),
        ),
    ]
