# Generated by Django 5.0.4 on 2024-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_rename_name_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='color',
            field=models.CharField(blank=True, default='0,0,0', max_length=200, null=True, verbose_name='Cor rgb ex 0,0,0'),
        ),
    ]
